# Generated by Django 3.1.3 on 2021-05-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event/')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('detail', models.TextField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='project/')),
                ('date', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField()),
                ('detail', models.TextField()),
                ('amount_required', models.IntegerField()),
                ('progress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Regisration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='usermedia/')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('Full_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_no', models.CharField(max_length=11)),
                ('dob', models.DateField(null=True)),
                ('department', models.CharField(max_length=100)),
                ('Passing_Year', models.DateField()),
                ('is_active', models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('status', models.CharField(choices=[('isPublic', 'isPublic'), ('isNotPublic', 'isNotPublic')], default='none', max_length=200)),
                ('designation', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('reponsibities', models.CharField(max_length=500)),
                ('time_stamp', models.DateField(auto_now=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='testimonial/')),
                ('desc', models.TextField()),
                ('status', models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
            ],
        ),
    ]
