# Generated by Django 3.1.3 on 2021-09-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azka', '0002_schoolinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regisration',
            name='Full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='regisration',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='regisration',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='regisration',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regisration',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='regisration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='usermedia/'),
        ),
        migrations.AlterField(
            model_name='regisration',
            name='phone_no',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='regisration',
            name='reponsibities',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='regisration',
            name='status',
            field=models.BooleanField(default=False, verbose_name='public or private'),
        ),
    ]
