# Generated by Django 3.1.3 on 2021-09-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azka', '0003_auto_20210917_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regisration',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='regisration',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
