# Generated by Django 3.1.3 on 2021-09-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azka', '0004_auto_20210917_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regisration',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='usermedia/'),
        ),
    ]
