# Generated by Django 3.1.3 on 2021-09-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azka', '0005_auto_20210917_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regisration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='usermedia/'),
        ),
    ]
