# Generated by Django 3.1.3 on 2021-09-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azka', '0006_auto_20210917_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regisration',
            name='image',
            field=models.ImageField(default='abc', upload_to='usermedia/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='regisration',
            name='password',
            field=models.CharField(max_length=16),
        ),
    ]
